import type { Metadata } from "next";
import "./globals.css";
import { MswInitializer } from "@/components/MSWInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {process.env.NEXT_PUBLIC_API_ENV === 'mock' && <MswInitializer />}
        {children}
      </body>
    </html>
  );
}
