# 1. 빌드
FROM openjdk:21-jdk-slim AS build

WORKDIR /app

# 필수 패키지 설치
RUN apt-get update && apt-get install -y findutils

# Gradle 실행에 필요한 파일 먼저 복사 (캐싱 최적화)
COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle build.gradle
COPY settings.gradle settings.gradle

# 실행 권한 부여
RUN chmod +x gradlew

# 의존성 미리 다운로드 (캐싱)
RUN ./gradlew dependencies --no-daemon

# 전체 프로젝트 복사
COPY . .

# gradlew 권한 부여
RUN chmod +x gradlew

# 빌드 실행 (테스트 포함)
RUN ./gradlew build --no-daemon

# 2. 실행
FROM openjdk:21-jdk

WORKDIR /app

# 명확한 이름으로 jar 파일 복사
COPY --from=build /app/build/libs/*.jar lightreborn-backend.jar

CMD ["java", "-jar", "lightreborn-backend.jar"]